import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';

import 'services/auth_service.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';

// If you later add Firebase options generated by the Firebase CLI, import them
// and pass to Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Initialize Firebase - this will be a no-op if you don't provide options
  try {
    await Firebase.initializeApp();
  } catch (e) {
    // If Firebase isn't configured yet that's fine - our fake AuthService will work
    debugPrint('Firebase initialize error (ignored): $e');
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => AuthService(),
      child: MaterialApp(
        debugShowCheckedModeBanner: false,
        title: 'Login Demo',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue),
        ),
        home: const RootPage(),
      ),
    );
  }
}

class RootPage extends StatelessWidget {
  const RootPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Consumer<AuthService>(
      builder: (context, auth, _) {
        // Show Home when signed in, otherwise Login screen
        if (auth.isSignedIn) {
          return const HomeScreen();
        }
        return const LoginScreen();
      },
    );
  }
}
